# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formn.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

class Ui_MainWindow(QtWidgets.QWidget):
    mysignal = QtCore.pyqtSignal(int)  # сигнал об ошибке
    mysignal1 = QtCore.pyqtSignal(int)  # сигнал об уведомлении
    def on_mysignal1(self,id):
        msg = QMessageBox()
        msg.setWindowTitle("Успех!!!")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("iconka.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        msg.setWindowIcon(icon)
        if id == 1:
            msg.setText(
                "Ключевая последовательность сгенерирована и её копия сохранена в указанном вами файле, в выбранной вами директории.")
        elif id == 2:
            msg.setText(
                "Ключевая последовательность сгенерирована и сохранена в директории, в которой установлена эта программа, в файле sp.txt")
        elif id == 3:
            msg.setText("Ключевая последовательность успешно считана.")
        elif id == 4:
            msg.setText("Ключевая последовательность успешно скопирована.")
        msg.setIcon(QMessageBox.Information)
        msg.exec_()
    def on_mysignal(self, id):
        msg = QMessageBox()
        msg.setWindowTitle("Ошибка!!!")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("iconka.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        msg.setWindowIcon(icon)
        if id == 1:
            msg.setText(
                "Ключевая последовательность не сгенерирована!!! Сгенерируйте ключевую последовательность или загрузите её!!")
        elif id == 2:
            msg.setText("Длинна текста превышает длину ключевой последовательности!")
        elif id == 3:
            msg.setText("Произошла ошибка при считывании ключевой последовательности!!!")
        msg.setIcon(QMessageBox.Warning)
        msg.exec_()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(800, 681)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("iconka.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        #MainWindow.setMinimumSize(QtCore.QSize(800, 620))
        MainWindow.setStyleSheet("QMainWindow{\n"
" background-color: black;\n"
"}\n"
"QWidget{\n"
" background-color: black;\n"
"color:red;\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(136, 138, 133);\n"
"    color: rgb(238, 238, 236);\n"
"}\n"
"QLabel{\n"
"    color: rgb(238, 238, 236);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(off.png);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    image: url(on.png);\n"
"}\n"
"QTextEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 576))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1448, 54))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(1430, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(510, 10, 111, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 10, 111, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(130, 10, 361, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(770, 10, 311, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(0, 10, 113, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(1100, 10, 331, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 2, 0, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(0, 0, -1, -1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBox_2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.gridLayout.addLayout(self.formLayout_3, 15, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(330, 20, 782, 21))
        self.label_5.setObjectName("label_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(720, 20, 61, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.frame_2, 17, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setEnabled(True)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.gridLayout.addLayout(self.formLayout, 12, 0, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout.addWidget(self.textEdit_2, 4, 0, 1, 1)
        #MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.mysignal.connect(self.on_mysignal)
        self.mysignal1.connect(self.on_mysignal1)
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OBK"))
        self.pushButton.setText(_translate("MainWindow", "зашифровать"))
        self.pushButton_2.setText(_translate("MainWindow", "расшифровать"))
        self.pushButton_3.setText(_translate("MainWindow", "Сгенерировать ключевую последовательность"))
        self.pushButton_5.setText(_translate("MainWindow", "загрузить ключевую последовательность"))
        self.pushButton_6.setText(_translate("MainWindow", "скопировать ключевую последовательность"))
        self.label.setText(_translate("MainWindow", "Входные данные"))
        self.label_4.setText(_translate("MainWindow", "Сделать копию файла с  ключевой последовательностью"))
        self.label_5.setText(_translate("MainWindow", "© Иван КоZлоV"))
        self.pushButton_4.setText(_translate("MainWindow", "?"))
        self.label_2.setText(_translate("MainWindow", "Выходные данные"))
        self.label_3.setText(_translate("MainWindow", "Сгенерировать ключевую последовательность по длине \n"
" оригинального текста"))
